name: "Bundle Check"
on:
  pull_request:
    branches:
      - "master"
jobs:
  check:
    name: "Bundle Check"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout the current branch"
        uses: "actions/checkout@v3"
      - name: "Setup Node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 18
      - name: "Install Node modules"
        run: "npm ci"
      - name: "Generate new bundle"
        run: "npm run package"
      - name: "Verify new bundle matches existing"
        run: "git diff --exit-code --name-only dist/"
      - name: "Show message instructing how to commit new bundle"
        if: failure()
        run: echo "::error title=Bundle has changed::The bundle has changed since the last commit and the new changes must be committed as part of this PR. Please run 'npm run package' and commit the results to your PR alongside your existing changes."
