name: 'Lint'
on:
  pull_request:
    branches:
      - 'master'
jobs:
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@v3'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 18
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Run lint'
        run: 'npm run lint'