name: 'Run tests'
on:
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    name: 'Tests (Node ${{ matrix.node_version }})'
    strategy:
      matrix:
        node_version: [16, 18]
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@v3'
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: ${{ matrix.node_version }}
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Run tests'
        run: 'npm run test'